file_uploader:
    front:
        target_url: '/api/upload/'
        chunk_size: 1048576
        simultaneous_uploads: 3
    back:
        destination_dir: ''
        temp_dir: 'temp/'
        upload_directory: '%kernel.project_dir%/%env(resolve:UPLOADS_PARENT)%/uploads'
