security:
    access_control:
        #- { path: '^/catalogue/node/item/resource/\d{11}_\d{1,3}.bool', requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/catalogue/node/item/resources/presets/$, methods: [POST], roles: ROLE_USER, requires_channel: https }
        - { path: ^/catalogue/node/item/resource/thumbnails, roles: ROLE_USER, requires_channel: https }
        - { path: ^/catalogue/node/item/resource, methods: [PATCH], roles: ROLE_WRITER, requires_channel: https }
        - { path: ^/usermanager, roles: ROLE_ADMIN , requires_channel: https }
        - { path: ^/api/links/get, roles: IS_AUTHENTICATED_ANONYMOUSLY , requires_channel: https }
        - { path: ^/api/links/, roles: ROLE_USER, requires_channel: https }
        - { path: ^/garbage/node/(remove|restore|add|update), roles: ROLE_GARBAGE_ADMIN, requires_channel: https }
        - { path: ^/, methods: [PATCH, POST], roles: ROLE_WRITER, requires_channel: https }
        - { path: ^/, roles: ROLE_USER , requires_channel: https }
