<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20181030080433 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE catalogue_node (id VARCHAR(11) NOT NULL, parent_id VARCHAR(11) DEFAULT NULL, name VARCHAR(255) NOT NULL, INDEX IDX_2E4A2E92727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE catalogue_node_item (id VARCHAR(11) NOT NULL, node_id VARCHAR(11) NOT NULL, name VARCHAR(255) DEFAULT NULL, INDEX IDX_DF1FF842460D9FD7 (node_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE resource (id INT AUTO_INCREMENT NOT NULL, item_id VARCHAR(11) NOT NULL, path VARCHAR(255) NOT NULL, username VARCHAR(255) NOT NULL, preset INT NOT NULL, type INT NOT NULL, chunk_path VARCHAR(255) DEFAULT NULL, created_on VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, src_filename VARCHAR(255) NOT NULL, is1c TINYINT(1) DEFAULT \'0\' NOT NULL, is_deleted TINYINT(1) DEFAULT \'0\' NOT NULL, is_default TINYINT(1) DEFAULT \'0\' NOT NULL, priority INT DEFAULT 0 NOT NULL, size_px VARCHAR(255) DEFAULT NULL, size_bytes BIGINT NOT NULL, comment VARCHAR(255) DEFAULT NULL, autogenerated TINYINT(1) NOT NULL, gid INT DEFAULT NULL, extension VARCHAR(255) DEFAULT NULL, INDEX IDX_BC91F416126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(25) NOT NULL, password VARCHAR(64) NOT NULL, email VARCHAR(254) NOT NULL, is_active TINYINT(1) NOT NULL, permissions VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649F85E0677 (username), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE upload (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, completed TINYINT(1) NOT NULL, total_chunks BIGINT NOT NULL, completed_chunks BIGINT NOT NULL, file_hash VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, item_id BIGINT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE catalogue_node ADD CONSTRAINT FK_2E4A2E92727ACA70 FOREIGN KEY (parent_id) REFERENCES catalogue_node (id)');
        $this->addSql('ALTER TABLE catalogue_node_item ADD CONSTRAINT FK_DF1FF842460D9FD7 FOREIGN KEY (node_id) REFERENCES catalogue_node (id)');
        $this->addSql('ALTER TABLE resource ADD CONSTRAINT FK_BC91F416126F525E FOREIGN KEY (item_id) REFERENCES catalogue_node_item (id)');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE catalogue_node DROP FOREIGN KEY FK_2E4A2E92727ACA70');
        $this->addSql('ALTER TABLE catalogue_node_item DROP FOREIGN KEY FK_DF1FF842460D9FD7');
        $this->addSql('ALTER TABLE resource DROP FOREIGN KEY FK_BC91F416126F525E');
        $this->addSql('DROP TABLE catalogue_node');
        $this->addSql('DROP TABLE catalogue_node_item');
        $this->addSql('DROP TABLE resource');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE upload');
    }
}
