module.exports = {
  ABS_FILE_PATHS:[
    '1.jpg',
    '2.jpg',
    '3.jpg',
    '4.jpg',
  ],

  RESOURCE_TYPES:{
    main: 1,
    add: 2,
    original: 3,
  },

  MAX_SLEEP: 30000,
  DEBUG_SLEEP: 1000,
  DEBUG: false,
  SHORT_WAIT: 200,
  WAIT: 400,
  LONG_WAIT: 4000,

  SITE_URL: 'http://localhost:8000',
  PAGE_UPLOAD: '/upload',
  PAGE_LINKS: '/account',
  PAGE_USERS: '/usermanager',

  USERS: {
    ADMIN: {
      LOGIN: 'efimov',
      PASSWORD: '300ljkkfhjd'
    },
    INCORRECT: {
      LOGIN: 'none',
      PASSWORD: 'none'
    }
  },
  FORM_DATA: {
    ITEM_NAME: 'Кружка',
    NODE_NAME: 'Кружка',
  },
  SELECTORS: {
    LOGIN: 'input[name="_username"]',
    PASSWORD: 'input[name="_password"]',
    LOGIN_ERROR_MESSAGE: '.auth__item.auth__item--error',
    LOGOUT_BUTTON: '.clogout-btn',
    LOADER: '.loading',
    NOTIFICATION_TOAST: '.notification.notification--toast',
    MENU_OPEN: '.menublock.open',
    MENU_COLLAPSE_BTN: 'i.menu-collapse',
    upload: {
      ITEM_SEARCH_FORM: '.item-search',
      ITEM_SEARCH_NAME_INPUT: '#srchinpt1',
      ITEM_SEARCH_NODE_INPUT: '#srchinpt2',
      ITEM_SEARCH_ITEM_CODE: '#srchinpt3',
      ITEM_SEARCH_NESTED_INPUT: '#srchinpt4',
      ITEM_SEARCH_SUBMIT_BTN: '#srchbtn',
      ITEM_LIST_ITEM: '.item-list .list-item',
      ITEM_LIST_FILTER: '#nodesearchinpt',
      CATALOGUE_TREE_SEARCH_VIEW: '.component-title__view-icons>i[data-view="3"]',
      CATALOGUE_TREE_LIST_VIEW: '.component-title__view-icons>i[data-view="1"]',
      CATALOGUE_TREE_TREE_VIEW: '.component-title__view-icons>i[data-view="2"]',
      CATALOGUE_TREE_LIST: '.catalogue-tree__view-inner',
      CATALOGUE_TREE_LIST_ITEM: '.list-view__cat_item[data-node]',
      CATALOGUE_TREE_LIST_ROOT: '.catalogue-tree__crumbs .crumbs__crumb:first-child',
      CATALOGUE_TREE_TREE_NODE_ANCHOR: '.jstree-anchor',
      CATALOGUE_TREE_TREE_NODE: '.jstree-node',
      CATALOGUE_TREE_TREE_NODE_DELETED: '.jstree-node.deleted',
      CATALOGUE_TREE_TREE_CHILDREN: '.jstree-children',
      CATALOGUE_TREE_LIST_UP: '.list-view__cat_item:not([data-node])',
      RESOURCE_LIST_ITEM: '.existing-files__file',
      DOWNLOAD_POOL_BTN: '.item-section-switcher[data-pool="1"]',
      UPLOAD_POOL_BTN: '.item-section-switcher[data-pool="2"]',
      DOWNLOAD_ALL_BTN: '.download-all-btn',
      UPLOAD_ALL_BTN: '.upload-pool__upload-all',
      BROWSE_FILES_BTN: '.browse-files-btn',
      UPLOAD_FILES_BTN: '.upload-files-btn',
      GARBAGE_SWITCH: '.collection-tabs__tab--garbage',
      RESOURCE_LIST_VIEW_TYPES:{
        large: '.item-view button[data-view="0"]',
        small: '.item-view button[data-view="1"]',
        table: '.item-view button[data-view="2"]',
      },
      RESOURCE_TILE_BTN: {
          download: '.dl-now',
          download_queue: '.dl-cart-add',
          open_tab: '.open-in-tab',
          copy_url: '.get-url',
      },
      RESOURCE:{
        ADDITIONAL_FILE_OPTION_SELECTED: 'option[selected][value="2"]',
        ORIGINAL_FILE_OPTION_SELECTED: 'option[selected][value="3"]',
        TYPE_SELECT: '.edit-input select',
        PRIORITY_BTN: '.edit-input__priority-btn',
        ADDITIONAL_TYPE_OPTION: '.edit-input option[value="2"]',
        MAIN_TYPE_OPTION: '.edit-input option[value="1"]',
        UPDATE_RESOURCES_BTN: 'button.update-resources',
        PRESET: '.info__info-field--preset-done',
      },
      NODE_CRUD:{
        SHOW_DELETED: '.show-deleted-nodes input[type="checkbox"]',
        ADD_BTN: '.btn.crud-add',
        RENAME_BTN: '.btn.crud-rename',
        DELETE_BTN: '.btn.crud-delete',
        ADD_INPUT: '.crud-controls--add input[name="name"]',
        RENAME_INPUT: '.crud-controls--rename input[name="name"]',
        SUBMIT: '.crud-controls button'
      },
    },
    linkmanager: {
      ADD_LINK_BTN: ".link-list .add-button",
      RESOURCE_SEARCH_ITEM_NAME: ".resource-search-form #root_item_search_name",
      RESOURCE_SEARCH_NODE_NAME: ".resource-search-form #root_item_search_parent_name",
      RESOURCE_SEARCH_SEARCH_NESTED: ".resource-search-form #root_item_search_search_nested",
      RESOURCE_SEARCH_ITEM_CODE: ".resource-search-form #root_item_search_code",
      RESOURCE_SEARCH_RESOURCE_ID: ".resource-search-form #root_resource_search_id",
      RESOURCE_SEARCH_PRESET_ID: ".resource-search-form #root_resource_search_preset",
      RESOURCE_SEARCH_TYPE_ID: ".resource-search-form #root_resource_search_type",
      RESOURCE_SEARCH_SUBMIT: ".resource-search-form button[type=submit]",
      RESOURCE_SEARCH_RESULT: ".resource.list-item",
      RESOURCE_SEARCH_SELECT_ALL: ".resource-search-results button[name=button]",
      LINK_ADD_SUBMIT: '.link-add-form .confirmator-button',
      COLLAPSE_ADDER_BTN: '.collapse-link-adder',
      LINK_DONE: '.link-list .link', 
    },
    notloading: {
      ITEM_LIST: ".item-list .view-inner__container:not(.loading)",
      NODE_LIST: ".catalogue-tree__view-inner:not(.loading)",
      RESOURCE_SEARCH_RESULTS: ".resource-search-results:not(.loading)",
      UNFINISHED_UPLOADS: ".item-uploads__unfinished:not(.loading)",
      RESOURCE_LIST: ".item-resources:not(.loading)",
      LINK_LIST: ".link-list .component-body:not(.loading)"
    }
  },
  SELECTORS_XPATH:{
    ORIGINAL_FILE: '//div[@class="item-view"]//option[@selected][@value="3"]/../../..',
    ADDITIONAL_FILE: '//div[@class="item-view"]//option[@selected][@value="2"]/../../..',
    MAIN_FILE: '//div[@class="item-view"]//option[@selected][@value="1"]/../../..',
    CATALOGUE_TREE_NODE: '//a[@class="jstree-anchor"]',
  },
};
